version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: recipe-sharing-container
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: recipe_sharing_app
    ports:
      - "7500:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
